<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_pulsa extends CI_Model
{

    public $table = 'kode_pulsa';
    public $id = 'id';
    public $order = 'DESC';
    public $url = 'https://portalpulsa.com/api/connect/';
         
          public $portal_userid = 'portal-userid: P163966';
          public $portal_key = 'portal-key: ed9ed3024c8d589c54bdb4c03c35e2b5';
          public $portal_secret = 'portal-secret: cff218abf8adaf112b80d694984464a667af9aad2a7ad3e3edf2b7811df85abe';
    function __construct()
    {
        parent::__construct();
    }

    function api(){
        $url = $this->url;

$header = array(
    $this->portal_userid,
    $this->portal_key, 
    $this->portal_secret, );
$data = array(
    'inquiry' => 'S', 
    'url'=>$url,'header'=>$header
    );

return $data;
    }
    function rajabiller(){
        $curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://rajabiller.fastpay.co.id/transaksi/json_devel.php',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
    "method"  : "rajabiller.balance",
    "uid": "SP310923",
    "pin": "228078",
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));

$response = curl_exec($curl);
curl_close($curl);
return json_decode($response, true);
    }
  
    // get all
    function get_code_pln()
    {

        $this->db->where('kategori','pln');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
     function get_all()
    {

     $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_kode_pulsa(){
       $this->db->where('kategori','pulsa');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();   
    }
    public function get_harga($code)
    {
        $this->db->where('kode', $code);
        $result = $this->db->get('kode_pulsa')->row(); 
        return $result;
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Testimoni_model.php */
/* Location: ./application/models/Testimoni_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 19:34:19 */
/* http://harviacode.com */